metadata:
  name: sample-nodejs-v2
  namespace: testing

service:
  name: nodejs-service-v2
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

configmapData:
  HOST_DB: mongo
  PORT_DB: 27017
  NAME_DB: elyadata
  PORT: 8080


image:
    repository: marwenguesmii/nodejsapp-2
    tag: "2.0"
    pullPolicy: Always

spec:
  replicasCout: 2
  restartPolicy: OnFailure
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  containers:
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    readinessProbe:
      httpGet:
        path: /healthzRead
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
    livenessProbe:
      httpGet:
        path: /healthzLive
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30




ingress:
  enabled: true
  name: nodejs-ingress-v2
  className: ""
  annotations: {}
  rules:
    - host: elyadata-devops-1.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: nodejs-service-v2
                port:
                  number: 8080

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30


